import pandas as pd
import matplotlib.pyplot as plt
import sys

train_data = pd.read_csv(sys.argv[1], sep = ',')
test_data = pd.read_csv(sys.argv[2], sep = ',')


train_agg = train_data.groupby(['day', 'hour', 'week'])['Global_active_power', 'Voltage', 'Global_reactive_power', 'Global_intensity'].agg(['mean', 'min', 'max']).reset_index()


test_agg = test_data.groupby(['day', 'hour', 'week'])['Global_active_power', 'Voltage', 'Global_reactive_power', 'Global_intensity'].agg(['mean', 'min', 'max']).reset_index()


plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Global_active_power']['mean'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Mean active power')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Global_active_power']['mean'], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Mean active power')
plt.savefig('Mean active power.png')

plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Global_active_power']['max'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Max active power')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Global_active_power']['max'], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Max active power')
plt.savefig('Max active power.png')

plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Voltage']['mean'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Mean Voltage')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Voltage']['mean'], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Mean Voltage')
plt.savefig('Mean Voltage.png')

plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Voltage']['max'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Max Voltage')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Voltage']['max'], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Max Voltage')
plt.savefig('Max Voltage.png')

plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Global_intensity']['mean'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Mean Global_intensity')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Global_intensity']['mean'], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Mean Global_intensity')
plt.savefig('Mean Global_intensity.png')

plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Global_intensity']['max'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Max Global_intensity')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Global_intensity']['max'], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Max Global_intensity')
plt.savefig('Max Global_intensity.png')


plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Voltage']['min'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Min Voltage')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Voltage']['min'], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Min Voltage')
plt.savefig('Min Voltage.png')



plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Global_active_power']['min'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Min active power')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Global_active_power']['min'], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Min active power')
plt.savefig('Min active power.png')

plt.figure(figsize=(20, 5))
plt.subplot(1, 2, 1)
plt.scatter(train_agg['week'], train_agg['Global_intensity']['min'], marker='o')
plt.title('Original data')
plt.xlabel('week')
plt.ylabel('Min Global_intensity')
plt.subplot(1, 2, 2)
plt.scatter(test_agg['week'], test_agg['Global_intensity']['min], marker='o')
plt.title('Test data')
plt.xlabel('week')
plt.ylabel('Min Global_intensity')
plt.savefig('Min Global_intensity.png')